(define *pipe* (open-output-file (car (command-line))))
(define *stdio* console-i/o-port)
(define *delimiter* #\newline)
(define *environment* (the-environment))
(define *scmutils* (environment-bound? *environment* 'D))
(define *silence* '*silence*)
(define *id* 0)

(define (*get-id*)
  (set! *id* (1+ *id*)))

(define (*send* . args)
  (write-char #\[ *pipe*)
  (if (pair? args)
    (let ((type (car args)) (data (cdr args)))
      (write type *pipe*)
      (let iter ((data data))
        (write-char #\, *pipe*)
        (write-string (car data) *pipe*)
        (if (pair? (cdr data))
            (iter (cdr data))))))
  (write-char #\] *pipe*)
  (write-char *delimiter* *pipe*)
  (flush-output *pipe*))
